name: Build, Scan & Push to Amazon ECR

on:

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Tag Docker Image
        working-directory: app
        run: |
        
           REPO=abbas-app
           TAG=latest
           REGISTRY=${{ steps.login-ecr.outputs.registry }}
           IMAGE_URI=$REGISTRY/$REPO:$TAG
           docker build -t $IMAGE_URI .
           docker tag    $IMAGE_URI $IMAGE_URI

      - name: Scan with Trivy Action
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref:   ${{ steps.login-ecr.outputs.registry }}/abbas-app:latest
          format:      table
          exit-code:   '1'
          severity:    CRITICAL

      - name: Push Docker Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/abbas-app:latest
