name: Terraform Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - run: pip install checkov

      - run: |
          curl -sL https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 \
            -o tfsec
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/

      - name: Run Checkov Scan
        working-directory: terraform
        run: checkov -d . --quiet --skip-check ALL
        continue-on-error: true

      - name: Run tfsec Scan
        working-directory: terraform
        run: tfsec --format json --out tfsec-report.json --soft-fail .
        continue-on-error: true

      - name: Save Reports
        working-directory: terraform
        run: checkov -d . --quiet --output junitxml --skip-check ALL > checkov-report.xml || true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            terraform/checkov-report.xml
            terraform/tfsec-report.json

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -backend-config=backend.tfvars

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan 

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
